# Generated by Django 5.0.2 on 2024-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=3000)),
                ('article_image', models.ImageField(upload_to='article_image/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
