# Generated by Django 5.0.4 on 2024-04-10 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_article_articlemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
