# Generated by Django 5.0.2 on 2024-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sales_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
