# Generated by Django 5.0.2 on 2024-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productmodel_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='ingredients',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
