# Generated by Django 5.0.4 on 2024-04-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_manager_productmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='ingredients',
            field=models.TextField(max_length=400),
        ),
    ]
