# Generated by Django 5.0.4 on 2024-04-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productmodel_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image_product',
            field=models.URLField(max_length=1000),
        ),
    ]
