# Generated by Django 5.0.2 on 2024-03-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='products_to_buy',
            new_name='products',
        ),
    ]
