# Generated by Django 5.0.2 on 2024-03-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_checkoutshippingaddressmodel'),
        ('orders', '0004_alter_orderproductmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.checkoutshippingaddressmodel'),
        ),
    ]
