# Generated by Django 5.0.2 on 2024-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordermodel_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
