# Generated by Django 5.0.2 on 2024-04-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_ordermodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.IntegerField(blank=True, default='4240132171', null=True),
        ),
    ]
