# Generated by Django 5.0.2 on 2024-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_ordermodel_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.IntegerField(blank=True, default='2969142171', null=True),
        ),
        migrations.AlterField(
            model_name='usershippingaddressmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
