# Generated by Django 5.0.4 on 2024-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_ordermodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.IntegerField(blank=True, default='3439852171', null=True),
        ),
    ]
