# Generated by Django 5.0.4 on 2024-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_ordermodel_is_sent_alter_ordermodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.IntegerField(blank=True, default='2032952171', null=True),
        ),
    ]
