# Generated by Django 5.0.2 on 2024-03-11 17:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_storeusermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeusermodel',
            name='date_of_birth',
            field=models.DateField(error_messages='Please enter your date of birth: YYYY-MM-DD.', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))]),
        ),
    ]
