# Generated by Django 5.0.2 on 2024-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_storeusermodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeusermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
