# Generated by Django 5.0.2 on 2024-03-13 10:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_storeusermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeusermodel',
            name='date_of_birth',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))]),
        ),
    ]
