# Generated by Django 5.0.2 on 2024-03-19 14:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_storeusermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeusermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1))]),
        ),
    ]
