# Generated by Django 5.0.2 on 2024-03-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_checkoutshippingaddressmodel_user_and_more'),
        ('orders', '0006_alter_ordermodel_shipping_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutShippingAddressModel',
        ),
    ]
