# Generated by Django 5.0.2 on 2024-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_checkoutshippingaddressmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershippingaddressmodel',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
